apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-gke-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: gitops-gke-app
          env:
            - name: ENVIRONMENT
              value: "prod"