apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
namespace: dev
images:
  - name: us-central1-docker.pkg.dev/gitops-gke-pipeline-503620/gitops-gke-app/gitops-gke-app
    newTag: c7e3736fd0463a8ac4cd6ea5de9189939f595ba0